publishing {
    publications {
        mavenJava(MavenPublication) {
            groupId = 'com.github.asana'
            artifactId = 'webpush-java-asana-fork'

            from components.java
            artifact sourcesJar
            artifact javadocJar
            pom {
                name = 'webpush-java-asana-fork'
                description = 'A Web Push library for Java (Asana fork).'
                url = 'https://github.com/Asana/webpush-java'
                scm {
                    connection = 'scm:git:git@github.com:Asana/webpush-java.git'
                    developerConnection = 'scm:git:git@github.com:Asana/webpush-java.git'
                    url = 'git@github.com:Asana/webpush-java.git'
                }
                licenses {
                    license {
                        name = 'MIT License'
                        url = 'https://opensource.org/licenses/MIT'
                    }
                }
                developers {
                    developer {
                        id = 'martijndwars'
                        name = 'Martijn Dwars'
                        email = 'ikben@martijndwars.nl'
                    }
                }
            }
        }
    }
    repositories {
        maven {
            url = uri("${buildDir}/repo")
        }
    }
}
